export const PRISMA_EDITOR_OPTIONS = {
  minimap: { enabled: true },
  fontSize: 14,
  fontFamily:
    "'JetBrains Mono', 'Fira Code', 'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, 'Courier New', monospace",
  fontLigatures: true,
  scrollbar: {
    alwaysConsumeMouseWheel: false,
  },
  lineNumbers: "on",
  wordWrap: "on",
  automaticLayout: true,
  scrollBeyondLastLine: false,
  padding: { top: 16, bottom: 16 },
  renderWhitespace: "selection",
  bracketPairColorization: { enabled: true },
  guides: {
    bracketPairs: true,
    indentation: true,
  },
  suggest: {
    showKeywords: true,
    showSnippets: true,
    showFunctions: true,
    showFields: true,
    showVariables: true,
    showClasses: true,
    showModules: true,
    showProperties: true,
    showEnums: true,
    showEnumMembers: true,
    showTypeParameters: true,
    snippetsPreventQuickSuggestions: false,
    filterGraceful: true,
    localityBonus: true,
  },
  quickSuggestions: {
    other: "inline",
    comments: false,
    strings: false,
  },
  quickSuggestionsDelay: 300,
  parameterHints: {
    enabled: true,
    cycle: true,
  },
  autoClosingBrackets: "always",
  autoClosingQuotes: "always",
  autoIndent: "full",
  iPadShowKeyboard: false,
  acceptSuggestionOnCommitCharacter: true,
  acceptSuggestionOnEnter: "off",
  tabCompletion: "on",
  wordBasedSuggestions: "allDocuments",
  folding: true,
  foldingStrategy: "indentation",
  showFoldingControls: "always",
  matchBrackets: "always",
  selectionHighlight: true,
  occurrencesHighlight: "singleFile",
  cursorBlinking: "blink",
  cursorStyle: "line",
  smoothScrolling: true,
  tabSize: 2,
  insertSpaces: true,
  formatOnPaste: true,
  formatOnType: true,
  multiCursorModifier: "ctrlCmd",
  mouseWheelZoom: true,
  linkedEditing: true,
  codeLens: true,
  inlineSuggest: {
    enabled: false,
    showToolbar: "never",
  },
  ariaLabel: "Prisma Schema Editor",
} as const;
